# Generated by Django 2.1.7 on 2019-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190506_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goal_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='goal_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
