# Generated by Django 2.1.7 on 2019-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190508_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goal_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goal_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
