# Generated by Django 2.1.7 on 2019-05-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190508_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='accounts.Club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Metric')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Metric')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
