# Generated by Django 2.1.7 on 2019-05-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_configparser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configparser',
            name='nameField',
        ),
        migrations.AddField(
            model_name='configparser',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
