# Generated by Django 2.1.7 on 2019-05-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190516_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparser',
            name='leagueName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='configparser',
            name='metricsExclude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configparser',
            name='seasonName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
